// Chinese lunar and solar term calculation for the native popover.
// Exports: LunarCalendar, LunarDate
// Deps: Foundation Calendar and LocalDate
//
// Solar term days come from a packed table generated by
// packages/core-calendar/tools/generate-solar-term-table.ts (astronomy-engine
// apparent solar longitude read in UTC+8, cross-validated against the
// 寿星天文历 ephemeris). It must stay byte-identical to the TypeScript copy in
// packages/core-calendar/src/solar-term-table.ts.

import Foundation

struct LunarDate {
    let yearName: String
    let monthName: String
    let dayName: String
    let solarTerm: String?
}

final class LunarCalendar {
    // Same corrected table as packages/core-calendar/src/constants.ts:
    // 1996 = 0x05ac0 and 2060 = 0x092e0 (verified against astronomical new
    // moons in UTC+8; the widely circulated values are wrong for those years).
    private let yearData = [
        0x0b557, 0x06ca0, 0x0b550, 0x15355, 0x04da0, 0x0a5b0, 0x14573, 0x052b0,
        0x0a9a8, 0x0e950, 0x06aa0, 0x0aea6, 0x0ab50, 0x04b60, 0x0aae4, 0x0a570,
        0x05260, 0x0f263, 0x0d950, 0x05b57, 0x056a0, 0x096d0, 0x04dd5, 0x04ad0,
        0x0a4d0, 0x0d4d4, 0x0d250, 0x0d558, 0x0b540, 0x0b6a0, 0x195a6, 0x095b0,
        0x049b0, 0x0a974, 0x0a4b0, 0x0b27a, 0x06a50, 0x06d40, 0x0af46, 0x0ab60,
        0x09570, 0x04af5, 0x04970, 0x064b0, 0x074a3, 0x0ea50, 0x06b58, 0x05ac0,
        0x0ab60, 0x096d5, 0x092e0, 0x0c960, 0x0d954, 0x0d4a0, 0x0da50, 0x07552,
        0x056a0, 0x0abb7, 0x025d0, 0x092d0, 0x0cab5, 0x0a950, 0x0b4a0, 0x0baa4,
        0x0ad50, 0x055d9, 0x04ba0, 0x0a5b0, 0x15176, 0x052b0, 0x0a930, 0x07954,
        0x06aa0, 0x0ad50, 0x05b52, 0x04b60, 0x0a6e6, 0x0a4e0, 0x0d260, 0x0ea65,
        0x0d530, 0x05aa0, 0x076a3, 0x096d0, 0x04afb, 0x04ad0, 0x0a4d0, 0x1d0b6,
        0x0d250, 0x0d520, 0x0dd45, 0x0b5a0, 0x056d0, 0x055b2, 0x049b0, 0x0a577,
        0x0a4b0, 0x0aa50, 0x1b255, 0x06d20, 0x0ada0, 0x14b63, 0x09370, 0x049f8,
        0x04970, 0x064b0, 0x168a6, 0x0ea50, 0x06b20, 0x1a6c4, 0x0aae0, 0x092e0,
        0x0d2e3, 0x0c960, 0x0d557, 0x0d4a0, 0x0da50, 0x05d55, 0x056a0, 0x0a6d0,
        0x055d4, 0x052d0, 0x0a9b8, 0x0a950, 0x0b4a0, 0x0b6a6, 0x0ad50, 0x055a0,
        0x0aba4, 0x0a5b0, 0x052b0, 0x0b273, 0x06930, 0x07337, 0x06aa0, 0x0ad50,
        0x14b55, 0x04b60, 0x0a570, 0x054e4, 0x0d160, 0x0e968, 0x0d520, 0x0daa0,
        0x16aa6, 0x056d0, 0x04ae0, 0x0a9d4, 0x0a2d0, 0x0d150, 0x0f252, 0x0d520
    ]
    private let monthLabels = ["正", "二", "三", "四", "五", "六", "七", "八", "九", "十", "冬", "腊"]
    private let dayDigits = ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "初", "廿"]
    private let stems = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]
    private let branches = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"]
    private let termLabels = ["小寒", "大寒", "立春", "雨水", "惊蛰", "春分", "清明", "谷雨", "立夏", "小满", "芒种", "夏至", "小暑", "大暑", "立秋", "处暑", "白露", "秋分", "寒露", "霜降", "立冬", "小雪", "大雪", "冬至"]
    private let termOffsets = [0, 21208, 42467, 63836, 85337, 107014, 128867, 150921, 173149, 195551, 218072, 240693, 263343, 285989, 308563, 331033, 353350, 375494, 397447, 419210, 440795, 462224, 483532, 504758]
    private let termTableStartYear = 1949
    private let termTableEndYear = 2100
    private let termBaseDays = [4, 19, 3, 18, 4, 19, 4, 19, 4, 20, 4, 20, 6, 22, 6, 22, 6, 22, 7, 22, 6, 21, 6, 21]
    private let termTable = [
        "111122112122112121122111", "211122112122212221222221", "221122122222222222222222", "222212111121111121111111", // 1949–1952
        "111122112122112121122111", "211122112122212221222211", "221122122222212222222221", "222211111121111121111111", // 1953–1956
        "111122112122112121122111", "211122112122112121222211", "221122122222212222222221", "222111111121111111111111", // 1957–1960
        "111122112121112121111111", "211122112122112121222211", "221122122222212222222221", "222111111121111111111111", // 1961–1964
        "111122112121112121111111", "211122112122112121222211", "221122122222212222222221", "222111111111111111111111", // 1965–1968
        "111122112121112121111111", "211122112122112121222211", "221122122222212222222221", "222111111111111111111111", // 1969–1972
        "111122111121112121111111", "211122112122112121222211", "221122122222212221222221", "222111011111111111111111", // 1973–1976
        "111122111121111121111111", "211122112122112121122211", "211122122122212221222221", "222111011111111111111111", // 1977–1980
        "111122111121111121111111", "211122112122112121122111", "211122112122212221222221", "221111011111101111111111", // 1981–1984
        "111112111121111121111111", "111122112122112121122111", "211122112122112221222211", "221111011111101111111110", // 1985–1988
        "111111111121111111111111", "111122112121112121122111", "211122112122112121222211", "221111011111101111111110", // 1989–1992
        "111011111121111111111111", "111122112121112121111111", "211122112122112121222211", "221111011111101111111110", // 1993–1996
        "111011111111111111111111", "111122112121112121111111", "211122112122112121222211", "221111011111101111111110", // 1997–2000
        "111011111111111111111111", "111122112121112121111111", "211122112122112121222211", "221111011111101111111110", // 2001–2004
        "111011111111111111111111", "111122111121111121111111", "211122112122112121222211", "221111011111101110111110", // 2005–2008
        "111011011111111111111111", "111122111121111121111111", "211122112122112121122211", "221111011011101110111110", // 2009–2012
        "111011011111101111111111", "111122111121111121111111", "211122112122112121122111", "211111001011101110111110", // 2013–2016
        "110011011111101111111111", "111112111121111121111111", "111122112121112121122111", "211111001011001010111110", // 2017–2020
        "110011011111101111111110", "111111111121111111111111", "111122112121112121122111", "211111001011001010111100", // 2021–2024
        "110011011111101111111110", "111011111111111111111111", "111122112121112121111111", "211111001011001010111100", // 2025–2028
        "110011011111101111111110", "111011111111111111111111", "111122112121112121111111", "211111001011001010111100", // 2029–2032
        "110011011111101111111110", "111011111111111111111111", "111122111121111121111111", "211111001011001010111100", // 2033–2036
        "110011011111101111111110", "111011111111111111111111", "111122111121111121111111", "211111001011001010111100", // 2037–2040
        "110011011011101110111110", "111011011111111111111111", "111122111121111121111111", "211111001011001010011100", // 2041–2044
        "110011001011101110111110", "111011011111101111111111", "111122111121111121111111", "211111001010001010011000", // 2045–2048
        "100011001011001010111110", "110011011111101111111111", "111111111121111111111111", "111111001010001010011000", // 2049–2052
        "100011001011001010111110", "110011011111101111111111", "111111111111111111111111", "111111001010001010011000", // 2053–2056
        "100011001011001010111100", "110011011111101111111110", "111111111111111111111111", "111111001010001010000000", // 2057–2060
        "100011001011001010111100", "110011011111101111111110", "111011111111111111111111", "111111001010001010000000", // 2061–2064
        "100011001011001010111100", "110011011111101111111110", "111011111111111111111111", "111111000010000010000000", // 2065–2068
        "100011001011001010111100", "110011011011101110111110", "111011111111111111111111", "111111000010000010000000", // 2069–2072
        "100011001011001010011100", "110011011011101110111110", "111011011111101111111111", "111111000010000010000000", // 2073–2076
        "100011001011001010011100", "110011001011001110111110", "111011011111101111111111", "111111000010000010000000", // 2077–2080
        "100011001010001010011000", "110011001011001010111110", "110011011111101111111111", "111100000010000000000000", // 2081–2084
        "000011001010001010011000", "100011001011001010111110", "110011011111101111111111", "111100000000000000000000", // 2085–2088
        "000011001010001010011000", "100011001011001010111100", "110011011111101111111110", "111100000000000000000000", // 2089–2092
        "000011001010001010000000", "100011001011001010111100", "110011011111101111111110", "111000000000000000000000", // 2093–2096
        "000011001010000010000000", "100011001011001010111100", "110011011111101111111110", "111011111111111111111111", // 2097–2100
    ]

    func lunarDate(for date: LocalDate) -> LunarDate? {
        // The table starts at lunar new year 1949 (1949-01-29); earlier days
        // of 1949 belong to lunar year 1948, which it cannot represent.
        guard date.year >= 1949 && date.year <= 2100 else {
            return nil
        }
        guard date.year > 1949 || date.month > 1 || date.day >= 29 else {
            return nil
        }
        guard let parts = lunarParts(for: date) else {
            return nil
        }
        return LunarDate(
            yearName: yearName(parts.year),
            monthName: monthName(parts.month, isLeap: parts.isLeapMonth),
            dayName: dayName(parts.day),
            solarTerm: solarTerm(for: date)
        )
    }

    private func lunarParts(for date: LocalDate) -> (year: Int, month: Int, isLeapMonth: Bool, day: Int)? {
        var daySpan = daysSinceBase(date) + 1
        var lunarYear = 0
        for index in 0..<yearData.count {
            daySpan -= lunarYearDays(yearData[index])
            if daySpan <= 0 {
                lunarYear = 1949 + index
                daySpan += lunarYearDays(yearData[index])
                break
            }
        }
        guard lunarYear > 0 else {
            return nil
        }
        let data = yearData[lunarYear - 1949]
        let months = lunarYearMonths(data)
        for index in 0..<months.count {
            daySpan -= months[index]
            if daySpan <= 0 {
                let month = normalizedMonth(index, leapMonth(data))
                return (lunarYear, month.number, month.isLeap, daySpan + months[index])
            }
        }
        return nil
    }

    private func daysSinceBase(_ date: LocalDate) -> Int {
        let calendar = Calendar(identifier: .gregorian)
        let base = calendar.date(from: DateComponents(timeZone: TimeZone(secondsFromGMT: 0), year: 1949, month: 1, day: 29)) ?? Date()
        let current = calendar.date(from: DateComponents(timeZone: TimeZone(secondsFromGMT: 0), year: date.year, month: date.month, day: date.day)) ?? Date()
        return Int(current.timeIntervalSince(base) / 86_400)
    }

    private func leapMonth(_ data: Int) -> Int? {
        let month = data & 0x0f
        return month == 0 ? nil : month
    }

    private func leapMonthDays(_ data: Int) -> Int {
        leapMonth(data) == nil ? 0 : ((data & 0xf0000) == 0 ? 29 : 30)
    }

    private func lunarYearDays(_ data: Int) -> Int {
        var total = 0
        var mask = 0x8000
        while mask > 0x8 {
            total += (data & mask) == 0 ? 29 : 30
            mask >>= 1
        }
        return total + leapMonthDays(data)
    }

    private func lunarYearMonths(_ data: Int) -> [Int] {
        var months: [Int] = []
        var mask = 0x8000
        while mask > 0x8 {
            months.append((data & mask) == 0 ? 29 : 30)
            mask >>= 1
        }
        if let leap = leapMonth(data) {
            months.insert(leapMonthDays(data), at: leap)
        }
        return months
    }

    // With a leap month, `months` has 13 entries and the inserted leap slot is
    // at index `leap`. Slots before it are months 1…leap, the slot itself is
    // 闰{leap}月, and slots after it map back to their ordinal month number.
    private func normalizedMonth(_ index: Int, _ leap: Int?) -> (number: Int, isLeap: Bool) {
        guard let leap else {
            return (index + 1, false)
        }
        if leap > index { return (index + 1, false) }
        if leap == index { return (index, true) }
        return (index, false)
    }

    private func yearName(_ year: Int) -> String {
        "\(stems[(year - 4) % 10])\(branches[(year - 4) % 12])"
    }

    private func monthName(_ month: Int, isLeap: Bool) -> String {
        let label = monthLabels[max(0, min(month - 1, monthLabels.count - 1))]
        return isLeap ? "闰\(label)" : label
    }

    private func dayName(_ day: Int) -> String {
        if day < 11 { return "\(dayDigits[10])\(dayDigits[day - 1])" }
        if day < 20 { return "\(dayDigits[9])\(dayDigits[day - 11])" }
        if day == 20 { return "\(dayDigits[1])\(dayDigits[9])" }
        if day < 30 { return "\(dayDigits[11])\(dayDigits[day - 21])" }
        return "\(dayDigits[2])\(dayDigits[9])"
    }

    // Valid independently of the lunar table range (e.g. 1949-01-01…28).
    func solarTerm(for date: LocalDate) -> String? {
        let first = (date.month - 1) * 2
        if date.day == solarTermDay(year: date.year, index: first) {
            return termLabels[first]
        }
        if date.day == solarTermDay(year: date.year, index: first + 1) {
            return termLabels[first + 1]
        }
        return nil
    }

    private func solarTermDay(year: Int, index: Int) -> Int {
        if year >= termTableStartYear, year <= termTableEndYear {
            let row = termTable[year - termTableStartYear]
            let offsetChar = row[row.index(row.startIndex, offsetBy: index)]
            return termBaseDays[index] + (Int(String(offsetChar)) ?? 0)
        }
        // Outside the table the legacy linear formula is used; it is only
        // accurate to about ±1 day and exists so distant calendar browsing
        // stays populated. It reads the result in UTC to stay byte-identical
        // with the TypeScript fallback in core-calendar.
        let base = Date(timeIntervalSince1970: -2_208_549_300)
        let offset = Double(year - 1900) * 31_556_925.9747 + Double(termOffsets[index]) * 60
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0) ?? .current
        return calendar.component(.day, from: base.addingTimeInterval(offset))
    }
}
